import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "highlight.js/styles/github-dark.css"; // シンタックスハイライト
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      {/* min-h-screen: 画面いっぱいに広げる, bg-gray-50: 薄いグレー背景 */}
      <body className={`${inter.className} min-h-screen flex flex-col bg-gray-50 text-gray-900`}>
        <Header />
        
        {/* max-w-3xl: 最大幅を制限, mx-auto: 中央寄せ */}
        <main className="flex-1 w-full max-w-3xl mx-auto px-4 py-8">
          {children}
        </main>
        
        <Footer />
      </body>
    </html>
  );
}